server:
  port: ${SERVER_PORT:0} # Variable de entorno para el puerto

spring:
  application:
    name: justificativo-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
